---
- name: Converge
  hosts: all
  vars:
    sentry_domain: bugs.example.com
    sentry_repo_token: 9fb0a313928fad2a9b9173b6c70a26044524b142
    sentry_database_name: bugs_sentry
    sentry_database_password: '123'
    sentry_database_uri: db.example.com
    sentry_database_user: bugs_sentry_user
    sentry_label: bugs_sentry
    sentry_secret_key: '321'
    sentry_smtp_host: smtp.mailgun.org
    sentry_smtp_password: '123'
    sentry_smtp_port: "587"
    sentry_smtp_user: postmaster@bugs.example.com
    ldap_organization: example
    ldap_domain: ldap.example.com
    ldap_admin_dn: dn.admin.ldap.example.com
    ldap_admin_password: '123'
    ldap_user_dn: dn.user.ldap.example.com
    users: []
  tasks:
    - name: "Include sentry"
      include_role:
        name: "sentry"
