---
# tasks file for rclone
- name: Install necessary packages/libraries
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rclone_packages }}"

- name: Create rclone directory
  file:
    path: "{{ rclone_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0766

- name: Download rclone
  get_url:
    url: "{{ rclone_download_url }}"
    dest: "{{ rclone_download_dir }}"
    force: no

- name: Unarchive rclone download
  unarchive:
    src: "{{ rclone_download_dir }}/{{ rclone_download_file }}"
    dest: "{{ rclone_download_dir }}"
    remote_src: yes

- name: Install rclone
  copy:
    remote_src: "yes"
    src: "{{ rclone_download_dir }}/{{ rclone_current }}/rclone"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Configure rclone
  template:
    src: "rclone_conf.j2"
    dest: "{{ rclone_config }}"
    owner: root
    group: root
    mode: 0600

- name: Create sync script for files
  template:
    src: "sync_script.j2"
    dest: "{{ rclone_sync_script }}"
    owner: root
    group: root
    mode: 0770

- name: Ensure sync of file
  cron:
    name: Sync files to storage
    minute: 30
    job: "{{ rclone_sync_script }}"
    state: present
    user: root
