---
ansible_support_packages:
  - slapd
  - ldap-utils
  - libldap2-dev
  - libsasl2-dev
  - libssl-dev
  - python3-pip
  - python3-dev
  - python-setuptools
  - gcc

python_pip_packages:
  - python-ldap
