---
ldap_admin_group: 'admins'
ldap_users_group: 'users'
ldap_dn_admin_group: 'ou={{ ldap_admin_group }},{{ ldap_base }}'
ldap_dn_users_group: 'ou={{ ldap_users_group }},{{ ldap_base }}'
ldap_dn_bind: 'cn=admin,{{ ldap_base }}'
ldap_dn_external: 'gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
