---
django_version: "{{ django_version }}"
django_repo_url: "https://{{ django_repo_domain }}/{{ django_repo_org }}/{{ django_repo_name }}"
django_release_url: "{{ django_repo_url }}/archive/refs/tags/{{ django_version }}.tar.gz?token={{ django_repo_token }}"

django_name: django
django_user: "{{ django_name }}"
django_group: "{{ django_user }}"
django_dir: "/home/www/{{ django_project }}"
django_app_dir: "{{ django_dir }}/app"
