---
django_version: 0.1
django_repo_url: "https://{{ django_repo_domain }}/api/v1/repos/{{ django_repo_org }}/{{ django_repo_name }}"
django_release_url: "{{ django_repo_url }}/archive/{{ django_version }}.tar.gz?token={{ django_repo_token }}"

django_user: www_data
django_group: www_data
django_dir: "/home/www/{{ django_project }}"
django_app_dir: "{{ django_dir }}/app"
django_static_dir: "{{ django_dir }}/static"
django_project_src: src
django_working_dir: "{{ django_app_dir }}/{{ django_project_src }}"

django_dirs:
  - "{{ django_static_dir }}"

django_http_listen_addr: 0.0.0.0
django_http_port: 8000

django_commands: []
django_fixtures: []
