---
- name: Converge
  hosts: all
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    gitea_salt: '123'
    gitea_database_password: '321'
    gitea_domain: 'git.example.com'
    gitea_database_uri: 'db.example.com'
    gitea_database_user: 'db_user'
    gitea_database_name: 'db_name'
    gitea_smtp_host: 'smtp.example.com'
    gitea_smtp_port: '587'
    gitea_smtp_user: 'postmaster@example.com'
    gitea_smtp_password: '123'
    gitea_ldap_host: 'ldap.example.com'
    gitea_ldap_port: '386'
    gitea_ldap_user_dn: 'cn=%s,ou=Users,dc=example,dc=com'
  roles:
    - role: gitea
