---
- name: Converge
  hosts: all
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    postgresql_databases:
      - name: db_name
    postgresql_users:
      - name: db_user
        password: 123
        db: db_name
    postgresql_hba_entries:
      - type: local
        database: all
        user: postgres
        auth_method: peer
      - type: local
        database: all
        user: all
        auth_method: peer
      - type: host
        database: all
        user: all
        address: '127.0.0.1/32'
        auth_method: md5
      - type: host
        database: all
        user: all
        address: '::1/128'
        auth_method: md5
  roles:
    - role: postgresql
