---
dependency:
  name: galaxy
  enabled: False
driver:
  name: podman
lint:
  name: yamllint
platforms:
  - name: prometheus-instance
    image: ubuntu:18.04
    privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
